version: 0.2

# env:
#   variables:
#     STAGE: dev
#     REGION: us-east-1
#     CLUSTER_NAME: eks-spinnaker
#     NAME: spinnaker

phases:
  install:
    commands:
      - echo Install started on `date`

      - echo Download and install aws-iam-authenticator
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$HOME/bin:$PATH
      - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc

      - echo Verify the installation of aws-iam-authenticator
      - aws-iam-authenticator help

      - echo Download and configure eksctl
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - mv /tmp/eksctl /usr/local/bin

      - echo Verify the installation
      - eksctl help

  build:
    commands:
      - echo Create the Amazon EKS cluster for Spinnaker
      - $stage/.terraform/modules/$NAME/scripts/manage_cluster.sh $cluster_name $AWS_REGION
